// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1) {
  return window['go']['media']['Media']['Emit'](arg1);
}

export function GetAlbumData(arg1) {
  return window['go']['media']['Media']['GetAlbumData'](arg1);
}

export function GetAlbumImage(arg1) {
  return window['go']['media']['Media']['GetAlbumImage'](arg1);
}

export function GetAlbums(arg1) {
  return window['go']['media']['Media']['GetAlbums'](arg1);
}

export function GetAudio(arg1) {
  return window['go']['media']['Media']['GetAudio'](arg1);
}

export function GetContents(arg1) {
  return window['go']['media']['Media']['GetContents'](arg1);
}

export function GetDirs(arg1) {
  return window['go']['media']['Media']['GetDirs'](arg1);
}

export function GetStandardDirs() {
  return window['go']['media']['Media']['GetStandardDirs']();
}

export function RemoveDir(arg1) {
  return window['go']['media']['Media']['RemoveDir'](arg1);
}

export function ScanForAudio(arg1) {
  return window['go']['media']['Media']['ScanForAudio'](arg1);
}

export function SearchAudio(arg1, arg2) {
  return window['go']['media']['Media']['SearchAudio'](arg1, arg2);
}

export function StartUp(arg1) {
  return window['go']['media']['Media']['StartUp'](arg1);
}
