// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {context} from '../models';

export function GetAlbumData(arg1:string):Promise<media.ReturnType>;

export function GetAlbumImage(arg1:string):Promise<media.ReturnType>;

export function GetAlbums(arg1:string):Promise<media.ReturnType>;

export function GetAudio(arg1:string):Promise<media.ReturnType>;

export function GetContents(arg1:string):Promise<media.ReturnType>;

export function GetDirs(arg1:string):Promise<media.ReturnType>;

export function ScanForAudio(arg1:string):Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;
