// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sharedTypes} from '../models';
import {context} from '../models';

export function Emit(arg1:string):Promise<void>;

export function GetAlbumData(arg1:string):Promise<sharedTypes.ReturnType>;

export function GetAlbumImage(arg1:string):Promise<sharedTypes.ReturnType>;

export function GetAlbums(arg1:string):Promise<sharedTypes.ReturnType>;

export function GetAudio(arg1:string):Promise<sharedTypes.ReturnType>;

export function GetContents(arg1:string):Promise<sharedTypes.ReturnType>;

export function GetDirs(arg1:string):Promise<sharedTypes.ReturnType>;

export function GetStandardDirs():Promise<sharedTypes.ReturnType>;

export function RemoveDir(arg1:string):Promise<void>;

export function ScanForAudio(arg1:string):Promise<void>;

export function SearchAudio(arg1:string,arg2:Array<string>):Promise<sharedTypes.ReturnType>;

export function StartUp(arg1:context.Context):Promise<void>;
