// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbumImage(arg1) {
  return window['go']['media']['Media']['GetAlbumImage'](arg1);
}

export function GetAlbums() {
  return window['go']['media']['Media']['GetAlbums']();
}

export function GetAudio(arg1) {
  return window['go']['media']['Media']['GetAudio'](arg1);
}

export function GetContents(arg1) {
  return window['go']['media']['Media']['GetContents'](arg1);
}

export function GetDirs(arg1) {
  return window['go']['media']['Media']['GetDirs'](arg1);
}

export function ScanForAudio(arg1) {
  return window['go']['media']['Media']['ScanForAudio'](arg1);
}

export function StartUp(arg1) {
  return window['go']['media']['Media']['StartUp'](arg1);
}
