// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {player} from '../models';
import {context} from '../models';

export function GetMetadata():Promise<any>;

export function GetPosition():Promise<any>;

export function GetStatus():Promise<player.PlayerStatus>;

export function LoadMusic(arg1:string):Promise<any>;

export function SetPosition(arg1:number):Promise<void>;

export function SetSpeed(arg1:number):Promise<any>;

export function SetVolume(arg1:number):Promise<any>;

export function StartUp(arg1:context.Context):Promise<void>;

export function ToggleMute():Promise<any>;

export function TogglePlay():Promise<any>;
