// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';
import {context} from '../models';

export function GetQueue(arg1:queue.filter):Promise<queue.ReturnType>;

export function StartUp(arg1:context.Context):Promise<void>;
