// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQueue(arg1) {
  return window['go']['queue']['Queue']['GetQueue'](arg1);
}

export function StartUp(arg1) {
  return window['go']['queue']['Queue']['StartUp'](arg1);
}
