// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';
import {context} from '../models';

export function AddToPlaylist(arg1:number,arg2:number):Promise<void>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:number):Promise<void>;

export function GetPlaylist(arg1:number):Promise<playlist.ReturnType>;

export function GetPlaylists():Promise<playlist.ReturnType>;

export function RemoveFromPlaylist(arg1:number,arg2:number):Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;

export function UpdatePlaylistName(arg1:number,arg2:string):Promise<void>;
