// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToFavorites(arg1) {
  return window['go']['playlist']['Playlist']['AddToFavorites'](arg1);
}

export function AddToPlaylist(arg1, arg2) {
  return window['go']['playlist']['Playlist']['AddToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1) {
  return window['go']['playlist']['Playlist']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['playlist']['Playlist']['DeletePlaylist'](arg1);
}

export function Emit(arg1) {
  return window['go']['playlist']['Playlist']['Emit'](arg1);
}

export function GetPlaylist(arg1) {
  return window['go']['playlist']['Playlist']['GetPlaylist'](arg1);
}

export function GetPlaylists() {
  return window['go']['playlist']['Playlist']['GetPlaylists']();
}

export function RemoveFromFavorites(arg1) {
  return window['go']['playlist']['Playlist']['RemoveFromFavorites'](arg1);
}

export function RemoveFromPlaylist(arg1, arg2, arg3) {
  return window['go']['playlist']['Playlist']['RemoveFromPlaylist'](arg1, arg2, arg3);
}

export function StartUp(arg1) {
  return window['go']['playlist']['Playlist']['StartUp'](arg1);
}

export function UpdatePlaylistName(arg1, arg2) {
  return window['go']['playlist']['Playlist']['UpdatePlaylistName'](arg1, arg2);
}
