// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function MaximizeApp():Promise<void>;

export function MinimizeApp():Promise<void>;

export function OpenMiniPlayer():Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;
