// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MaximizeApp() {
  return window['go']['app']['app']['MaximizeApp']();
}

export function MinimizeApp() {
  return window['go']['app']['app']['MinimizeApp']();
}

export function OpenMiniPlayer() {
  return window['go']['app']['app']['OpenMiniPlayer']();
}

export function StartUp(arg1) {
  return window['go']['app']['app']['StartUp'](arg1);
}
