// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dir} from '../models';
import {context} from '../models';

export function GetAudio(arg1:string):Promise<dir.ReturnType>;

export function GetContents(arg1:string):Promise<dir.ReturnType>;

export function GetDirs(arg1:string):Promise<dir.ReturnType>;

export function ScanForAudio(arg1:string):Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;
