// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudio(arg1) {
  return window['go']['dir']['Directory']['GetAudio'](arg1);
}

export function GetContents(arg1) {
  return window['go']['dir']['Directory']['GetContents'](arg1);
}

export function StartUp(arg1) {
  return window['go']['dir']['Directory']['StartUp'](arg1);
}
